-- Seed de teste do modelo rico: Manta Listrada Texturizada Arco-Íris Pastel.
-- (gerado a partir da análise da foto enviada)

INSERT INTO lessons (title, slug, description, technique, difficulty, duration_min,
                     cover_url, status, order_index, published_at, meta)
VALUES (
  'Manta Listrada Texturizada Arco-Íris Pastel',
  'manta-listrada-arco-iris-pastel',
  'Uma manta de crochê em listras pastel com textura densa de grupos (família Suzette/Sedge), trabalhada plana em carreiras com trocas de cor frequentes.',
  'crochet',
  'intermediate',
  NULL,
  'https://placehold.co/800x520/F6C6C0/2E2620/png?text=Manta+Arco-Iris+Pastel',
  'published',
  10,
  now(),
  '{"product_name":"Manta Listrada Texturizada Arco-Íris Pastel","overview":"Uma manta de crochê listrada em tons pastel, com textura densa tipo grãozinhos (pequenos grupos em V/concha inclinados, agrupados em carreiras deslocadas) em vez de buracos abertos de granny — o que indica um ponto de grupo da família Suzette/Sedge trabalhado plano, em carreiras, com trocas de cor frequentes.","difficulty_label":"Iniciante avançado → Intermediário","finished_size":"aproximadamente 100 × 130 cm (manta)","materials":["Fio peso worsted/aran (médio #4), acrílico macio ou mistura com algodão, acabamento fosco","~6–7 cores: 1 marfim/creme principal + 5–6 pastéis (pêssego, amarelo-manteiga, verde-sálvia, azul-céu, lavanda)","Agulha de crochê aprox. 5,0–5,5 mm (H/I)","Agulha de tapeçaria para arrematar; tesoura"],"color_sequence":"Ciclo arco-íris pastel repetido, com uma faixa estreita de marfim como descanso entre as cores: Marfim → Pêssego → Marfim → Amarelo-manteiga → Verde-sálvia → Azul-céu → Lavanda → Marfim → (repete). Cada faixa de cor tem cerca de 2 carreiras; as de marfim, cerca de 1–2 carreiras.","construction_method":"Trabalhada plana, em carreiras de ida e volta. Uma correntinha de base longa define a largura; as listras crescem carreira a carreira para ganhar comprimento. As cores são trocadas terminando o último ponto da carreira na cor nova e virando. A borda é feita por último ao redor dos quatro lados.","stitches":[{"name":"Grupo Sedge / Suzette (ponto baixo + ponto alto no mesmo ponto, pula 1)","confidence":"Média"},{"name":"Ponto alto (double crochet)","confidence":"Alta"},{"name":"Ponto baixo (single crochet)","confidence":"Alta"}],"pattern_analysis":"A unidade que se repete em cada carreira é um grupo de [1 pb + 1 pa no mesmo ponto, pula 1 ponto], dando o aspecto de tijolos deslocados porque cada carreira encaixa nos pares da anterior. Os relevos inclinados, tipo sementinha, e a ausência de buracos descartam a listra de granny clássica e favorecem essa família de grupos densos. As listras são horizontais e ocupam toda a largura; a diagonal visível na foto é só pela manta caindo sobre a borda do colchão. A borda parece ser uma volta simples de pb, possivelmente com um leve acabamento de conchinhas na borda inferior.","confidence_note":"O layout das listras, as trocas de cor e a construção em carreiras planas estão claros pela imagem; o ponto exato do grupo (Sedge/Suzette vs. Wattle) é a melhor leitura da textura, não uma certeza. Uma macro de alguns pontos permitiria definir o grupo com precisão."}'::jsonb
)
ON CONFLICT (slug) DO NOTHING;

-- Passos (blocos type='step') com os campos detalhados.
WITH l AS (SELECT id FROM lessons WHERE slug = 'manta-listrada-arco-iris-pastel')
INSERT INTO lesson_blocks (lesson_id, position, type, content)
SELECT l.id, s.position, 'step', s.content
FROM l, (VALUES
  (0, '{"number":1,"title":"Montar a base","goal":"Montar a largura total da manta com a carreira de base.","visual_description":"Uma longa correntinha horizontal de fio marfim esticada reta, com a agulha na ponta direita; uma carreira inicial uniforme e levemente elástica.","stitches_used":"Correntinha de base (ponto correntinha); conte um número par compatível com a repetição do grupo.","pattern_used":"Correntinha simples — múltiplo de 2 pontos mais a correntinha de virada.","expected_result":"Uma base de correntinhas reta e plana cobrindo a largura desejada da manta.","instruction":"Montar a largura total da manta com a carreira de base. Correntinha simples — múltiplo de 2 pontos mais a correntinha de virada.","image_url":"https://placehold.co/640x420/EADBCD/2E2620/png?text=Passo+1+Base"}'::jsonb),
  (1, '{"number":2,"title":"Primeira carreira de grupos","goal":"Trabalhar a primeira carreira de grupos texturizados e fixar o padrão do ponto.","visual_description":"Close da agulha entrando numa correntinha e puxando o fio para fazer um ponto baixo e um ponto alto no mesmo lugar, e então pulando uma correntinha — formando a primeira carreira de pequenos relevos inclinados em marfim.","stitches_used":"Grupo de ponto baixo + ponto alto, pula 1, repete até o fim.","pattern_used":"[(pb, pa) no mesmo ponto, pula 1 ponto] repetido até o fim; vire.","expected_result":"Uma carreira texturizada completa, com grupos tipo grãozinhos uniformemente espaçados ao longo da borda inferior.","instruction":"Trabalhar a primeira carreira de grupos texturizados e fixar o padrão do ponto. [(pb, pa) no mesmo ponto, pula 1 ponto] repetido até o fim; vire.","image_url":"https://placehold.co/640x420/F2D9C6/2E2620/png?text=Passo+2+Grupos"}'::jsonb),
  (2, '{"number":3,"title":"Formar a primeira listra","goal":"Trabalhar várias carreiras na mesma cor para formar a primeira listra sólida.","visual_description":"Uma amostra de poucas carreiras de altura, toda numa cor pastel (ex.: pêssego), com a textura bem visível em relevos densos e deslocados; as carreiras se empilham numa faixa caprichada.","stitches_used":"Mesma repetição do grupo pb + pa, encaixando os grupos nos pares da carreira anterior.","pattern_used":"Repita a carreira do Passo 2 por 2 carreiras a cada faixa de cor; os grupos ficam deslocados em relação à carreira anterior.","expected_result":"Uma listra pastel limpa e uniforme, com textura consistente e bordas laterais retas.","instruction":"Trabalhar várias carreiras na mesma cor para formar a primeira listra sólida. Repita a carreira do Passo 2 por 2 carreiras a cada faixa de cor; os grupos ficam deslocados em relação à carreira anterior.","image_url":"https://placehold.co/640x420/F6C6C0/2E2620/png?text=Passo+3+Listra"}'::jsonb),
  (3, '{"number":4,"title":"Trocar de cor","goal":"Trocar de cor de forma limpa para começar a próxima listra.","visual_description":"No fim da carreira, dois fios na borda — o pastel antigo terminando um ponto enquanto um novo fio marfim é puxado pela última laçada; a junção fica no fim da carreira e o trabalho é virado.","stitches_used":"Grupos como antes; troca de cor na última laçada do último ponto.","pattern_used":"Termine a carreira, troque a cor na última passada de fio, prenda a cor antiga e vire.","expected_result":"Uma transição de cor horizontal nítida, sem buracos, pronta para a próxima faixa.","instruction":"Trocar de cor de forma limpa para começar a próxima listra. Termine a carreira, troque a cor na última passada de fio, prenda a cor antiga e vire.","image_url":"https://placehold.co/640x420/F4E3B0/2E2620/png?text=Passo+4+Troca+de+cor"}'::jsonb),
  (4, '{"number":5,"title":"Repetir o ciclo de listras","goal":"Repetir o ciclo de listras para crescer o corpo todo da manta.","visual_description":"Um painel maior mostrando a sequência repetida — marfim, pêssego, marfim, amarelo, verde, azul, lavanda — em faixas pastel horizontais empilhadas, com a textura em relevo consistente do começo ao fim.","stitches_used":"Repetição contínua do grupo pb + pa com trocas de cor periódicas.","pattern_used":"Repita a sequência de cores (ver Sequência de Cores) até atingir o comprimento desejado.","expected_result":"Um tecido listrado retangular em tamanho real, tensão uniforme, laterais retas e faixas arco-íris separadas pelo creme.","instruction":"Repetir o ciclo de listras para crescer o corpo todo da manta. Repita a sequência de cores (ver Sequência de Cores) até atingir o comprimento desejado.","image_url":"https://placehold.co/640x420/B8D8C0/2E2620/png?text=Passo+5+Corpo"}'::jsonb),
  (5, '{"number":6,"title":"Acabamento e bordas","goal":"Finalizar as bordas e arrematar as pontas para uma manta caprichada.","visual_description":"A manta pronta esticada, com uma borda marfim caprichada nos quatro lados, pontas escondidas; opcionalmente um acabamento suave de conchinhas na borda inferior.","stitches_used":"Borda em ponto baixo (com aumentos uniformes nos cantos); acabamento opcional em ponto leque/concha; arremate com agulha de tapeçaria.","pattern_used":"1 volta de pb em todo o perímetro, 3 pb em cada canto; acabamento opcional [pula, leque de 5 pa, pula, pb] na borda inferior.","expected_result":"Uma manta finalizada limpa e firme, com bordas emolduradas e sem pontas soltas.","instruction":"Finalizar as bordas e arrematar as pontas para uma manta caprichada. 1 volta de pb em todo o perímetro, 3 pb em cada canto; acabamento opcional [pula, leque de 5 pa, pula, pb] na borda inferior.","image_url":"https://placehold.co/640x420/C9C0E8/2E2620/png?text=Passo+6+Bordas"}'::jsonb)
) AS s(position, content)
WHERE NOT EXISTS (
  SELECT 1 FROM lesson_blocks b WHERE b.lesson_id = (SELECT id FROM l) AND b.type = 'step'
);
