-- Pontos (stitches) server-driven: antes vinham de assets/data/stitches.json.
-- Agora ficam no Postgres pra poder gerenciar (e anexar vídeo da técnica) pelo painel.
CREATE TABLE IF NOT EXISTS stitches (
  id             text PRIMARY KEY,
  name_pt        text NOT NULL,
  name_en        text NOT NULL,
  abbrev         text NOT NULL DEFAULT '',
  technique      text NOT NULL CHECK (technique IN ('crochet','knit')),
  difficulty     text NOT NULL CHECK (difficulty IN ('beginner','intermediate','advanced')),
  categories     jsonb NOT NULL DEFAULT '[]',
  description    text NOT NULL DEFAULT '',
  steps          jsonb NOT NULL DEFAULT '[]',
  video_asset_id uuid REFERENCES assets(id) ON DELETE SET NULL,
  order_index    integer NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

INSERT INTO stitches (id, name_pt, name_en, abbrev, technique, difficulty, categories, description, steps, order_index) VALUES
('st-cr-001', 'Correntinha', 'Chain', 'corr / ch', 'crochet', 'beginner', '["base", "fundamento"]'::jsonb, 'Sequência de laçadas que forma a base da maioria dos projetos de crochê. Tudo começa por aqui.', '["Faça um nó corrediço na agulha.", "Passe o fio sobre a agulha de trás para frente.", "Puxe o fio através da laçada existente.", "Repita até obter o número de correntinhas desejado."]'::jsonb, 0),
('st-cr-002', 'Ponto baixíssimo', 'Slip stitch', 'pbx / sl st', 'crochet', 'beginner', '["base", "união"]'::jsonb, 'Ponto curto, usado para fechar carreiras circulares, unir partes e dar acabamento sem altura.', '["Insira a agulha no ponto desejado.", "Laçada sobre a agulha.", "Puxe o fio através do ponto e da laçada de uma só vez."]'::jsonb, 1),
('st-cr-003', 'Ponto baixo', 'Single crochet', 'pb / sc', 'crochet', 'beginner', '["base", "firme"]'::jsonb, 'Ponto fundamental do crochê. Forma tecido firme e denso, ideal para amigurumi, bolsas e bases.', '["Insira a agulha no próximo ponto.", "Laçada e puxe (duas laçadas na agulha).", "Laçada novamente e puxe através das duas laçadas."]'::jsonb, 2),
('st-cr-004', 'Meio ponto alto', 'Half double crochet', 'mpa / hdc', 'crochet', 'beginner', '["base"]'::jsonb, 'Altura intermediária entre o ponto baixo e o ponto alto. Equilíbrio entre firmeza e fluidez.', '["Laçada antes de inserir a agulha.", "Insira no próximo ponto, laçada e puxe (três laçadas na agulha).", "Laçada e puxe através das três laçadas de uma vez."]'::jsonb, 3),
('st-cr-005', 'Ponto alto', 'Double crochet', 'pa / dc', 'crochet', 'beginner', '["base", "aberto"]'::jsonb, 'Tecido com bom caimento, perfeito para shawls, mantas e roupas leves.', '["Laçada na agulha.", "Insira no próximo ponto, laçada e puxe (três laçadas).", "Laçada e puxe através de duas laçadas.", "Laçada e puxe através das duas restantes."]'::jsonb, 4),
('st-cr-006', 'Ponto alto duplo', 'Treble crochet', 'pad / tr', 'crochet', 'intermediate', '["alto", "aberto"]'::jsonb, 'Ponto bem alto, ótimo para xales, gola e peças de verão.', '["Duas laçadas na agulha.", "Insira no ponto, laçada e puxe (quatro laçadas).", "Laçada e puxe através de duas, três vezes seguidas."]'::jsonb, 5),
('st-cr-007', 'Ponto pipoca', 'Popcorn stitch', 'pop', 'crochet', 'intermediate', '["textura", "decorativo"]'::jsonb, 'Forma pequenos bojos texturizados. Excelente para detalhes em mantas, almofadas e peças infantis.', '["Faça 5 pontos altos no mesmo ponto base.", "Retire a agulha do último ponto e insira no primeiro alto.", "Pegue a laçada solta e puxe através, fechando o grupo."]'::jsonb, 6),
('st-cr-008', 'Ponto puff', 'Puff stitch', 'puff', 'crochet', 'intermediate', '["textura"]'::jsonb, 'Volumoso e macio, lembra pequenas almofadas no tecido. Lindo em mantas para bebê.', '["Laçada, insira no ponto e puxe um fio longo (3 laçadas).", "Repita 3 a 5 vezes no mesmo ponto.", "Laçada e puxe através de todas as laçadas da agulha.", "Feche com 1 correntinha."]'::jsonb, 7),
('st-cr-009', 'Ponto leque', 'Shell stitch', 'leque', 'crochet', 'intermediate', '["decorativo", "aberto"]'::jsonb, 'Vários pontos altos no mesmo ponto base formam um leque elegante. Comum em shawls.', '["No ponto indicado, faça 5 pontos altos consecutivos.", "Pule a quantidade de pontos indicada.", "Continue na próxima base."]'::jsonb, 8),
('st-cr-010', 'Cluster', 'Cluster', 'cl', 'crochet', 'advanced', '["textura"]'::jsonb, 'Grupo de pontos altos não finalizados, unidos em um único topo. Base para muitos pontos texturizados.', '["Faça pontos altos sem finalizar, deixando a última laçada na agulha.", "Quando tiver o número desejado, laçada final.", "Puxe através de todas as laçadas da agulha."]'::jsonb, 9),
('st-cr-011', 'Granny square', 'Granny square', 'granny', 'crochet', 'beginner', '["motivo", "clássico"]'::jsonb, 'Quadradinho clássico do crochê. Combine vários para formar mantas, almofadas e roupas patchwork.', '["Anel mágico ou 4 correntinhas fechadas em círculo.", "Carreira 1: 3 grupos de 3 pontos altos com 3 correntinhas entre eles.", "Carreiras seguintes: nos cantos faça 2 grupos de 3 PA separados por 3 correntinhas."]'::jsonb, 10),
('st-cr-012', 'Anel mágico', 'Magic ring', 'anel', 'crochet', 'beginner', '["fundamento", "amigurumi"]'::jsonb, 'Início ajustável para projetos circulares. Permite fechar o centro sem buraco.', '["Faça uma laçada solta com o fio.", "Insira a agulha e puxe o fio principal através.", "Trabalhe os pontos por dentro do anel.", "Puxe a ponta solta para fechar o centro."]'::jsonb, 11),
('st-tr-001', 'Montagem simples', 'Long-tail cast on', 'montagem', 'knit', 'beginner', '["base", "fundamento"]'::jsonb, 'Forma elástica de iniciar pontos na agulha de tricô. Versátil para a maioria dos projetos.', '["Calcule a ponta longa (3x a largura da peça).", "Faça um nó corrediço na agulha.", "Forme a posição de funda com os dedos.", "Puxe a laçada para cima e ajuste cada ponto."]'::jsonb, 12),
('st-tr-002', 'Ponto meia', 'Knit stitch', 'k / m', 'knit', 'beginner', '["base"]'::jsonb, 'Base do tricô. Forma o famoso V do direito da malha. Combinado, gera o ponto meia em rebatido (stockinette).', '["Insira a agulha direita pela frente do ponto, da esquerda para a direita.", "Passe o fio por trás da agulha direita.", "Puxe a laçada para frente.", "Deslize o ponto antigo para fora da agulha esquerda."]'::jsonb, 13),
('st-tr-003', 'Ponto tricô', 'Purl stitch', 'p / t', 'knit', 'beginner', '["base"]'::jsonb, 'Inverso do ponto meia. Combinado com ele forma toda a base do tricô plano e circular.', '["Mantenha o fio à frente do trabalho.", "Insira a agulha direita pela frente, da direita para a esquerda.", "Enrole o fio sentido anti-horário.", "Puxe a laçada para trás e solte o ponto antigo."]'::jsonb, 14),
('st-tr-004', 'Ponto jersey', 'Stockinette', 'jersey', 'knit', 'beginner', '["padrão", "fundamento"]'::jsonb, 'Alternância de uma carreira em meia e uma em tricô. Resultado liso no direito e enrolado nas bordas.', '["Carreira 1 (direito): todos os pontos em meia.", "Carreira 2 (avesso): todos os pontos em tricô.", "Repita as duas carreiras."]'::jsonb, 15),
('st-tr-005', 'Ponto elástico 1x1', '1x1 ribbing', 'rib 1x1', 'knit', 'beginner', '["padrão", "elástico"]'::jsonb, 'Elasticidade no acabamento de barras, punhos e gola. Alternância 1 meia, 1 tricô.', '["Monte número par de pontos.", "Carreira: *1 meia, 1 tricô*, repita até o fim.", "Continue todas as carreiras seguindo os pontos."]'::jsonb, 16),
('st-tr-006', 'Ponto arroz', 'Seed stitch', 'seed', 'knit', 'intermediate', '["textura"]'::jsonb, 'Alternância 1 meia 1 tricô, invertida a cada carreira. Cria textura granulada que lembra grãos de arroz.', '["Carreira 1: *1 meia, 1 tricô*, repita.", "Carreira 2: troque — sobre meia faça tricô, sobre tricô faça meia.", "Repita as duas carreiras."]'::jsonb, 17),
('st-tr-007', 'Tranças', 'Cable stitch', 'tr / cb', 'knit', 'advanced', '["textura", "decorativo"]'::jsonb, 'Pontos cruzados que formam tranças clássicas de tricô. Requer agulha auxiliar.', '["Passe 2 a 4 pontos para a agulha auxiliar.", "Posicione na frente ou atrás conforme o sentido da trança.", "Tricote os próximos pontos da agulha principal.", "Volte os pontos da agulha auxiliar e tricote."]'::jsonb, 18),
('st-tr-008', 'Aumento simples', 'Make one (M1)', 'aum / M1', 'knit', 'intermediate', '["aumento"]'::jsonb, 'Adiciona um ponto novo entre dois existentes sem deixar buraco aparente.', '["Levante a barra horizontal entre os dois últimos pontos.", "Coloque-a na agulha esquerda por trás.", "Tricote em meia pela perna de trás."]'::jsonb, 19),
('st-tr-009', 'Diminuição (k2tog)', 'Knit two together', 'k2tog', 'knit', 'beginner', '["diminuição"]'::jsonb, 'Reduz um ponto. Inclinação para a direita.', '["Insira a agulha direita pelos dois próximos pontos da esquerda.", "Trabalhe como uma única meia.", "Solte os dois pontos antigos juntos."]'::jsonb, 20),
('st-tr-010', 'Casa de botão', 'Buttonhole', 'casa', 'knit', 'intermediate', '["acabamento"]'::jsonb, 'Abertura no tecido para passar botões. Existem várias técnicas — a mais comum é a casa fechada em uma carreira.', '["Na posição, faça os pontos indicados.", "Tire pontos com aumento por laçada.", "Vire e feche o número necessário com cordão.", "Continue a carreira normalmente."]'::jsonb, 21)
ON CONFLICT (id) DO NOTHING;
