-- 100 variações de notificação de engajamento (EN) no pool de sorteio +
-- um agendamento "a cada 4h" (interval_minutes=240, use_pool=true).
-- O agendamento entra PAUSADO (enabled=false): ativar dispara push a cada 4h
-- para todos os usuários — ligue no painel quando quiser.
-- Dollar-quoting ($m$...$m$) evita escapar apóstrofos/emojis.

INSERT INTO notification_pool (title, body) VALUES
($m$Your hook is calling 🧶$m$, $m$A cozy stitch session is waiting. Open StitchMind and make a few rows.$m$),
($m$5 minutes, one row$m$, $m$Sneak in a quick row before your day gets busy. Tap to continue your project.$m$),
($m$Stitch of the day$m$, $m$Learn a new stitch today — it only takes a few minutes. Come see it!$m$),
($m$Don't break your streak 🔥$m$, $m$You're on a roll! Keep your making streak alive with a quick session.$m$),
($m$Pattern picked for you$m$, $m$We found a project you'll love. Open the app to take a peek.$m$),
($m$Tangle-free time$m$, $m$Unwind with a few stitches. Your next row is one tap away.$m$),
($m$New video lesson 🎥$m$, $m$Watch a step-by-step tutorial and try it yourself. Let's stitch!$m$),
($m$Where did we leave off?$m$, $m$Your project is waiting right where you stopped. Jump back in.$m$),
($m$Cozy crafting awaits$m$, $m$Grab your yarn and your favorite drink. Time to make something.$m$),
($m$Quick win for today$m$, $m$Finish one small section and feel great. Open StitchMind now.$m$),
($m$Yarn therapy 🧶$m$, $m$Stressful day? A few stitches can help. Tap to relax and create.$m$),
($m$Level up your stitches$m$, $m$Ready to try something new? A fresh technique is waiting for you.$m$),
($m$Your projects miss you$m$, $m$It's been a little while. Pick up right where you left off!$m$),
($m$Counting made easy$m$, $m$Lost your place? Use the row counter and keep going. Open the app.$m$),
($m$Make today count$m$, $m$One row a day adds up fast. Add yours now.$m$),
($m$Fresh inspiration inside$m$, $m$Browse new patterns and find your next make. Tap to explore.$m$),
($m$Coffee + crochet ☕$m$, $m$The perfect pair. Settle in for a few cozy rows.$m$),
($m$Learn it in minutes$m$, $m$A simple new stitch is ready for you. Come give it a try!$m$),
($m$Almost there!$m$, $m$Your project is close to done. Add a few rows and finish strong.$m$),
($m$Beat the scroll$m$, $m$Trade five minutes of scrolling for five minutes of stitching. Let's go!$m$),
($m$Today's crochet tip 💡$m$, $m$A small trick that makes a big difference. Open to learn it.$m$),
($m$Your next masterpiece$m$, $m$Start something new today. The perfect pattern is waiting.$m$),
($m$Hooks up!$m$, $m$Time for a stitching break. Your yarn is ready when you are.$m$),
($m$Keep those hands busy$m$, $m$A few stitches beat a restless evening. Tap to make.$m$),
($m$Stitch, relax, repeat$m$, $m$Your calm corner is one tap away. Come unwind.$m$),
($m$Don't lose your place$m$, $m$Save your spot and keep your project moving. Open StitchMind.$m$),
($m$A new technique for you$m$, $m$Expand your skills with today's featured stitch. Let's learn!$m$),
($m$Make something today$m$, $m$Even one row counts. Open the app and create.$m$),
($m$Your daily dose of cozy$m$, $m$Warm up with a quick stitching session. Tap in.$m$),
($m$Pattern of the day 📌$m$, $m$Today's pick is a quick and satisfying make. Come see it.$m$),
($m$Stuck on a stitch?$m$, $m$Watch a quick video and master it. We'll guide you row by row.$m$),
($m$Treat yourself to a row$m$, $m$You earned a creative break. Pick up your hook!$m$),
($m$Yarn night in 🌙$m$, $m$Wind down with a few rows before bed. Tap to relax.$m$),
($m$Progress feels good$m$, $m$Move your project forward today. Your future self will thank you.$m$),
($m$Tiny goal, big joy$m$, $m$Finish one section and smile. Start now in StitchMind.$m$),
($m$Your hooks are lonely$m$, $m$Give them some love with a quick make. Open the app.$m$),
($m$Learn something new 🧠$m$, $m$Today's stitch is easier than it looks. Come try it!$m$),
($m$Cozy up and create$m$, $m$Blanket, tea, and a few rows. Your perfect evening starts here.$m$),
($m$One more row?$m$, $m$You know you want to. Continue your project now.$m$),
($m$Make magic with yarn ✨$m$, $m$A small skein, a big idea. Let's get stitching.$m$),
($m$Beat boredom with yarn$m$, $m$Turn idle minutes into stitches. Tap to begin.$m$),
($m$Your project is waiting$m$, $m$Pick up where you left off and keep the momentum going.$m$),
($m$Today's quick make$m$, $m$A satisfying mini-project you can finish today. Open to start.$m$),
($m$Stitch your stress away$m$, $m$A few rows for a calmer mind. Come relax with us.$m$),
($m$New in the stitch library$m$, $m$Discover a technique you haven't tried yet. Tap to learn.$m$),
($m$Hook, line, and stitches$m$, $m$Your next favorite project is calling. Dive in!$m$),
($m$Crafternoon time$m$, $m$Make this afternoon count with a quick stitching session.$m$),
($m$Don't let the yarn wait$m$, $m$Your stash wants to become something beautiful. Start now.$m$),
($m$Five rows challenge$m$, $m$Can you do five rows today? Open the app and try!$m$),
($m$Your cozy reminder 🧶$m$, $m$Time to slow down and stitch. We saved your spot.$m$),
($m$Brighten your day$m$, $m$A little making goes a long way. Tap in and create.$m$),
($m$Skill up today$m$, $m$Practice makes progress. Try today's featured stitch.$m$),
($m$Your evening ritual$m$, $m$Tea, yarn, and a few peaceful rows. Begin in StitchMind.$m$),
($m$Make moves on your make$m$, $m$A few rows now, a finished project soon. Let's go!$m$),
($m$New pattern alert 🔔$m$, $m$Something fresh just for you. Open the app to check it out.$m$),
($m$Slow down and stitch$m$, $m$Give your mind a break with a calm session. Tap here.$m$),
($m$Yarn o'clock$m$, $m$It's the perfect time for a stitch. Your project is ready.$m$),
($m$Keep the rhythm going$m$, $m$Stitch by stitch, you're getting there. Add a row today.$m$),
($m$Craft your calm$m$, $m$Trade tension for texture. A few rows are waiting.$m$),
($m$Today's stitch tip$m$, $m$One quick tip to level up your work. Come learn it!$m$),
($m$Be proud of progress$m$, $m$Every row matters. Make yours now in StitchMind.$m$),
($m$A stitch a day 🧶$m$, $m$Small habits, big projects. Add today's row.$m$),
($m$Your make break$m$, $m$Step away from the screen and into your yarn. Tap to start.$m$),
($m$Finish that project$m$, $m$It's so close! A few more rows and it's done.$m$),
($m$Try this technique$m$, $m$Today's featured stitch is fun and quick. Give it a go!$m$),
($m$Unwind with yarn$m$, $m$Let the stitches melt the day away. Open the app.$m$),
($m$Cozy minutes await$m$, $m$A short, sweet stitching session is ready for you.$m$),
($m$Hook a little happy$m$, $m$A few rows can lift your mood. Come make something.$m$),
($m$Stitch break!$m$, $m$Reset with a quick creative moment. Your yarn is waiting.$m$),
($m$Master a new skill$m$, $m$Watch, learn, and stitch along. Today's lesson is ready.$m$),
($m$Your next row awaits$m$, $m$Don't keep your project waiting. Continue now!$m$),
($m$Make today cozy$m$, $m$Warm vibes and soft yarn. Start a quick session.$m$),
($m$Pattern made for you$m$, $m$A project that fits your vibe. Tap to discover it.$m$),
($m$Quick stitches, big smiles$m$, $m$A satisfying session in just minutes. Open the app.$m$),
($m$Don't drop a stitch$m$, $m$Keep your project on track. Jump back in now.$m$),
($m$Creative spark inside ✨$m$, $m$Need inspiration? We've got a pattern for you. Come look.$m$),
($m$Your hands want this$m$, $m$Put down the phone, pick up the hook. Let's stitch!$m$),
($m$Stitch and chill$m$, $m$The comfiest break of your day is one tap away.$m$),
($m$Make progress today$m$, $m$A row now beats a row never. Open StitchMind.$m$),
($m$New tutorial ready 🎥$m$, $m$Follow along and learn a new stitch. Tap to watch.$m$),
($m$Your project says hi 👋$m$, $m$It's waiting patiently. Add a few rows today.$m$),
($m$Yarn calls, you answer$m$, $m$A cozy session is calling your name. Come create.$m$),
($m$Tiny rows, big wins$m$, $m$Little by little, it gets done. Stitch a row now.$m$),
($m$Brew, hook, repeat ☕$m$, $m$Pour a cup and stitch a few rows. Open the app.$m$),
($m$Today's making moment$m$, $m$Carve out a few minutes to create. Your yarn is ready.$m$),
($m$Level up tonight$m$, $m$End your day with a new technique. Today's stitch awaits.$m$),
($m$Keep calm and crochet$m$, $m$A few stitches for a peaceful mind. Tap in.$m$),
($m$Your comfort craft$m$, $m$Soft yarn, easy rows, happy you. Start a session now.$m$),
($m$Stitch something lovely$m$, $m$A beautiful make is a few rows away. Come create.$m$),
($m$Don't ghost your yarn 👻$m$, $m$It misses you! Pick up your project today.$m$),
($m$Make it a stitch day$m$, $m$One row to start, more to follow. Open StitchMind.$m$),
($m$Quick pattern, big joy$m$, $m$A fast, satisfying make is ready. Tap to begin.$m$),
($m$Your daily stitch fix$m$, $m$Get your cozy fix with a few rows. We saved your spot.$m$),
($m$New stitch unlocked 🔓$m$, $m$Ready to learn something new? Today's stitch is waiting.$m$),
($m$Cozy hands, happy heart$m$, $m$A little making makes a big difference. Start now.$m$),
($m$Pick up where you left$m$, $m$Your rows are waiting. Continue your project in seconds.$m$),
($m$Stitch your way calm$m$, $m$Trade the noise for the rhythm of the hook. Tap here.$m$),
($m$A make a day$m$, $m$Keep your hands and heart happy. Add today's row.$m$),
($m$Your yarn adventure$m$, $m$Every project starts with one stitch. Make yours now!$m$),
($m$Time to make ✨$m$, $m$Your cozy crafting moment is here. Open StitchMind and stitch.$m$);

-- Agendamento "a cada 4 horas" usando o pool (sorteia uma mensagem por envio).
-- PAUSADO por padrão — ative no painel (Notificações → Agendados).
INSERT INTO scheduled_notifications
  (use_pool, target_type, schedule_kind, interval_minutes, timezone, enabled, next_run_at)
VALUES
  (true, 'all', 'interval', 240, 'America/Sao_Paulo', false, NULL);
